In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\ProgramData\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\ProgramData\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

NameError: name 'df' is not defined

In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behavior.csv'

In [4]:
import os

print(os.getcwd())

C:\Users\khush

In [5]:
print(os.listdir())

['.agents', '.anaconda', '.antigravity-ide', '.arduinoIDE', '.cache', '.conda', '.continuum', '.copilot', '.gemini', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.lesshst', '.local', '.mcp-auth', '.node_repl_history', '.platformio', '.streamlit', '.vscode', '.vscode-shared', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'cprag1.c', 'CrossDevice', 'Documents', 'Downloads', 'Favorites', 'google_drive_uploader', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TM.blf', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TM.blf.cnpf', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{5102e51d-e7bf-11ef-ac46-f105c5dc6be2}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled Folder', 'Untitled.ipynb', 'Untitled1.ipynb', 'Videos']

In [6]:
import os

print(os.listdir('Downloads'))

['-college id.pdf', '-VLSI-JULY-.pdf', '1photo.jpeg', '2photo.jpeg', 'Adidas US Sales Datasets.xlsx', 'Adidas_logo.png', 'Anaconda3-2026.07-1-Windows-x86_64.exe', 'analytics.png', 'Antigravity IDE.exe', 'Antigravity-x64 (1).exe', 'Antigravity-x64.exe', 'archive', 'archive.zip', 'arduino-ide_2.3.7_Windows_64bit.exe', 'arm.docx', 'arm1.pdf', 'ARM_Report.pdf', 'Books.csv', 'Cadence_Virt_VM_Incl_GPDK_Library', 'Cadence_Virt_VM_Incl_GPDK_Library.zip', 'card and thumbnail.png', 'CareerPilot Project.pdf', 'CareerPilot_AI_Project_Report_Chapters_5_to_14.docx', 'Certificate (1).pdf', 'Certificate (2).pdf', 'Certificate (3).pdf', 'certificate,Tata,Data Analytics.pdf', 'certificate.pdf', 'Chapter - 3 - Excel_Data_Analysts_Training.xlsx', 'checkout.png', 'ChromeSetup (2).exe', 'ChromeSetup.exe', 'codeblocks-20.03mingw-setup.exe', 'collegeID.jpeg', 'CT20265022447_Application_Form.pdf', 'Customers.csv', 'customer_behavior_dashboard.pbix', 'customer_behavior_sql_queries.sql', 'customer_shopping_behavior.csv', 'cv.pdf', 'data-governance.png', 'database (2).png', 'dataset (1).zip', 'dataset.zip', 'debug.log', 'desktop.ini', 'DiscordSetup.exe', 'economics.png', 'EDA_Example_Answer.docx', 'emailtcs.pdf', 'Employee-Management-Sample-Data.xlsx', 'excel_files_youtube.zip', 'Final Project ppt template_AICTE_March2026 (2) (1).pptx', 'Final Project ppt template_AICTE_March2026 (2) (2).pptx', 'Final Project ppt template_AICTE_March2026 (2).pptx', 'Firefox Installer.exe', 'GET PIVOT DATA. TRYxlsx.xlsx', 'Instructor_Slides_and_Notebooks (1).zip', 'Instructor_Slides_and_Notebooks (2).zip', 'Instructor_Slides_and_Notebooks (4).zip', 'Instructor_Slides_and_Notebooks.zip', 'Inventory-Records-Sample-Data.xlsx', 'kaggle project demo.mp4', 'keli4.EXE', 'khushi.docx', 'khushi.pdf', 'khushi.s.k.pdf', 'khushi.s.k_compressed.pdf', 'Khushi.S.K_ECE.pdf', 'Khushi.S.K_Falabella.pdf', 'Khushi.S.K_Karmic (1).pdf', 'Khushi.S.K_Karmic.pdf', 'khushi.s.k_Resume.pdf', 'Khushi_Infosys.pdf', 'Khushi_Kudagunti_DataAnalyst.docx', 'Khushi_Kudagunti_Resume.docx', 'Khushi_Kudagunti_Resume.pdf', 'Khushi_Kudagunti_Semiconductor.docx', 'Khushi_Kudagunti_SoftwareDeveloper.docx', 'khushi_resume1.docx', 'krupa_marksheet.pdf', 'Lab_Guide (1).zip', 'Lab_Guide.zip', 'laptop.png', 'lEETCODE SQL.pdf', 'LTspice64 (1).msi', 'LTspice64.msi', 'LTspice_OpAmpComparator_Project.cir', 'mingw-get-setup (1).exe', 'mingw-get-setup.exe', 'MJ_resume.pdf', 'Multiple Pivot Table try.xlsx', 'mysql-installer-community-8.0.46.0.msi', 'ngspice-45.2_64 (1).7z', 'ngspice-45.2_64.7z', 'nmap_portscan_gui-main', 'nmap_portscan_gui-main (1)', 'nmap_portscan_gui-main (1).zip', 'nmap_portscan_gui-main (2).zip', 'nmap_portscan_gui-main (3).zip', 'nmap_portscan_gui-main.zip', 'node-v22.13.1-x64.msi', 'Orders.csv', 'passportphoto.jpeg', 'PA_Resume..pdf', 'PBIDesktopSetup_x64.exe', 'pexels-carlos-oliva-1966452-3586966.jpg', 'pexels-pixabay-45853.jpg', 'photok.jpeg', 'photokk.jpeg', 'picture.jpeg', 'picturee.jpeg', 'Pivot Table Data.xlsx', 'postgresql-18.4-2-windows-x64.exe', 'Python Cheat Sheet - The Basics SN.pdf', 'python-3.13.1-amd64.exe', 'python-3.13.7-amd64.exe', 'python-manager-26.0 (1).msix', 'python-manager-26.0.msix', 'rating (3).png', 'report vlsi.pdf', 'resume (1).pdf', 'resume.new.pdf', 'resume.pdf', 'resume_26.docx', 'resume_new.docx', 'resume_new.pdf', 'revenue.png', 'SANJANAIB.pdf', 'simplileran.pdf', 'SMARTHIRE AI.pdf', 'sne resume.docx', 'sneha resume.docx', 'sql_basic certificate.pdf', 'star (1).png', 'Support_Guide.zip', 'Swiggy Raw Data Excel.xlsx', 'tcs.pdf', 'Unconfirmed 28841.crdownload', 'Unconfirmed 980623.crdownload', 'vbm.docx', 'vlsireport.pdf', 'VMware-workstation-full-17.5.2-23775571.exe', 'VSCodeUserSetup-x64-1.104.0.exe', 'VSCodeUserSetup-x64-1.96.4.exe', 'wallpaper.png', 'wallpaper2.png', 'WhatsApp Image 2025-04-24 at 12.07.10 PM.jpeg', 'WhatsApp Image 2025-04-24 at 12.15.03 PM.jpeg', 'WhatsApp Image 2026-06-12 at 10.45.04 PM.jpeg', 'Zoom_cm_fo42pnktZ9vvrZo4_mBqoXepy7pCBzdMfTJ-hXunzoBeqzVZRZ0I7f@6rwpvp2d8XQ6+-n9_k81cebe76458f4e36_.exe', '~$pcs1.docx', '~$s1done.docx']

In [7]:
import pandas as pd

df = pd.read_csv('Downloads/customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [10]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [12]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [1]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'Purchase Amount (USD)':'purchase_amount'})

NameError: name 'df' is not defined

In [2]:
df.columns

NameError: name 'df' is not defined

In [3]:
import pandas as pd
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'Purchase Amount (USD)':'purchase_amount'})

NameError: name 'df' is not defined

In [4]:
import pandas as pd

df = pd.read_csv('Downloads/customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(' ', '_')

df = df.rename(columns={
    'purchase_amount_(usd)': 'purchase_amount'
})

print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [6]:
# create a column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels)

In [7]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [8]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly':14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchase'].map(frequency_mapping)

KeyError: 'frequency_of_purchase'

In [9]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [10]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3863 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  promo_code_used          3900 non-null   str
 15  previous_purchases       3900 non-null   int64
 16  payment_method           3900 non-null   str
 17  frequency_of_purchases   3900 non-null   str
 18  age_group                3900 non-null   category
 19  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(13)
memory usage: 870.4 KB

In [12]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [13]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [14]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [16]:
#Connecting Python script to PostgreSQL

!pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg2_binary-2.9.13-cp314-cp314-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ---------- ----------------------------- 0.8/2.9 MB 3.1 MB/s eta 0:00:01
   --------------------- ------------------ 1.6/2.9 MB 3.4 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 3.9 MB/s  0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.13

In [17]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "amlan123" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

ModuleNotFoundError: No module named 'psycopg2'

In [1]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "amlan123" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv(
    'Downloads/customer_shopping_behavior.csv'
)

print(df.shape)
df.head()

(3900, 18)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
print(df.columns.tolist())
print(df.shape)

['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']
(3900, 18)

In [4]:
from sqlalchemy import create_engine

username = "postgres"
password = "YOUR_PASSWORD"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(
    f"Data successfully loaded into table '{table_name}' "
    f"in database '{database}'."
)

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [5]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "khushi"      # default user
password = "#Khushi2005" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")
Data successfully loaded into table 'customer' in database 'customer_behavior'.

SyntaxError: invalid syntax (2264696688.py, line 18)

In [6]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "khushi"      # default user
password = "#Khushi2005" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "khushi"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [7]:
from sqlalchemy import create_engine, text

username = "khushi"
password = "#Khushi2005"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

try:
    with engine.connect() as connection:
        connection.execute(text("SELECT 1"))
        print("Connection successful!")

except Exception as e:
    print(type(e).__name__)
    print(e)

OperationalError
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "khushi"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [8]:
from sqlalchemy import create_engine, text

username = "postgres"  # Change if needed
password = "#Khushi2005"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

with engine.connect() as connection:
    connection.execute(text("SELECT 1"))
    print("Connection successful!")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "customer_behavior" does not exist

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [9]:
from sqlalchemy import create_engine, text

username = "postgres"  # Change if needed
password = "#Khushi2005"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

with engine.connect() as connection:
    connection.execute(text("SELECT 1"))
    print("Connection successful!")

Connection successful!

In [10]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "#Khushi2005" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "customer_behavior"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [11]:
#Code for MySQL
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3